assets = {}

#IMAGENS

assets['tela_inicial'] = pygame.image.load('').convert()
assets['tela_inicial'] = pygame.transform.scale(assets[''], (, ))
assets['tela_vitoria'] = pygame.image.load('').convert()
assets['tela_vitoria'] = pygame.transform.scale(assets[''], (, ))
assets['tela_derrota'] = pygame.image.load('').convert()
assets['tela_derrota'] = pygame.transform.scale(assets[''], (, ))
assets['tela_fundo_escape1'] = pygame.image.load('').convert_alpha()
assets['tela_fundo_escape1'] = pygame.transform.scale(assets[''], (, ))
assets['tela_fundo_escape2'] = pygame.image.load('').convert_alpha()
assets['tela_fundo_escape2'] = pygame.transform.scale(assets[''], (, ))
assets['tela_fundo_escape3'] = pygame.image.load('').convert_alpha()
assets['tela_fundo_escape3'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape1'] = pygame.image.load('').convert_alpha()
assets['dica_escape1'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape2'] = pygame.image.load('').convert_alpha()
assets['dica_escape2'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape3'] = pygame.image.load('').convert_alpha()
assets['dica_escape3'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape4'] = pygame.image.load('').convert_alpha()
assets['dica_escape4'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape5'] = pygame.image.load('').convert_alpha()
assets['dica_escape5'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape6'] = pygame.image.load('').convert_alpha()
assets['dica_escape6'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape7'] = pygame.image.load('').convert_alpha()
assets['dica_escape7'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape8'] = pygame.image.load('').convert_alpha()
assets['dica_escape8'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape9'] = pygame.image.load('').convert_alpha()
assets['dica_escape9'] = pygame.transform.scale(assets[''], (, ))
assets['dica_escape10'] = pygame.image.load('').convert_alpha()
assets['dica_escape10'] = pygame.transform.scale(assets[''], (, ))
assets['barra_tempo'] = pygame.image.load('').convert_alpha()
assets['barra_tempo'] = pygame.transform.scale(assets[''], (, ))
assets['personagem'] = pygame.image.load('').convert_alpha()
assets['personagem'] = pygame.transform.scale(assets[''], (, ))

#SONS

pygame.mixer.music.load('')
pygame.mixer.music.set_volume()
assets['musica_fundo'] = pygame.mixer.Sound('')
assets['som_vitoria'] = pygame.mixer.Sound('')
assets['som_derrota'] = pygame.mixer.Sound('')
assets['som_andando'] = pygame.mixer.Sound('')
assets['som_usando_dica'] = pygame.mixer.Sound('')